brew install ag
brew install bash
brew install bat
brew install clementtsang/bottom/bottom
brew install git-delta
brew install exa
brew install fasd
brew install fd
brew install fzf
brew install gh
brew install git
brew install coreutils
brew install node
brew install noti
brew install neovim
brew install pass
brew install rename
brew install rg
brew install sc-im
brew install tldr
brew install tmux
brew install vim
brew install xpdf
